# Generated by Django 3.0.8 on 2020-08-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom du dossier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('short_name', models.CharField(max_length=10, verbose_name='Abbréviation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nom(s)')),
                ('matricule', models.CharField(max_length=10, verbose_name='Matricule')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('region_of_origin', models.CharField(max_length=100, verbose_name="Region d'origine")),
                ('father_name', models.CharField(max_length=255, verbose_name='Nom(s) du père')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Nom(s) de la mère')),
                ('gender', models.CharField(choices=[('female', 'Feminin'), ('male', 'Masculin')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('course_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='app.CourseOfStudy')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
            },
        ),
        migrations.AddField(
            model_name='courseofstudy',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_of_study', to='app.Department'),
        ),
        migrations.CreateModel(
            name='BachelorAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('academic_year', models.CharField(max_length=10, verbose_name='Année académique')),
                ('father_occupation', models.CharField(max_length=100, verbose_name='Occupation du père')),
                ('mother_occupation', models.CharField(max_length=100, verbose_name='Occupation de la mère')),
                ('parents_address', models.CharField(max_length=100, verbose_name='Adresse des parents')),
                ('bac_serial', models.CharField(max_length=25, verbose_name='Série Bac')),
                ('grade', models.CharField(max_length=50, verbose_name='Mention')),
                ('date_obtained', models.DateField(verbose_name="Année d'obtention")),
                ('entry_qualification', models.CharField(max_length=100, verbose_name="Diplôme d'entrée")),
                ('other_entry_qualification', models.CharField(blank=True, max_length=100, verbose_name="Autre diplôme d'entrée")),
                ('city', models.CharField(max_length=150, verbose_name='Ville')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('department_first_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_fc', to='app.Department')),
                ('department_second_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_sc', to='app.Department')),
                ('fd_course_study_fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_fd_cs_fc', to='app.CourseOfStudy', verbose_name='Premier parcours dans le premier departement choisi')),
                ('fd_course_study_sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_fd_cs_sc', to='app.CourseOfStudy', verbose_name='Deuxième parcours dans le premier departement choisi')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_level', to='app.Level', verbose_name='Niveau')),
                ('sd_course_study_fc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_sd_cs_fc', to='app.CourseOfStudy', verbose_name='Premier parcours dans le deuxième departement choisi')),
                ('sd_course_study_sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_sd_cs_sc', to='app.CourseOfStudy', verbose_name='Deuxième parcours dans le deuxième departement choisi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student', verbose_name='Etudiant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
