# Generated by Django 3.0.8 on 2020-09-16 09:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(max_length=150, verbose_name='Nom du fichier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Type du document',
                'verbose_name_plural': 'Types du document',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom du dossier')),
            ],
            options={
                'verbose_name': 'Dossier étudiant',
                'verbose_name_plural': 'Dossiers étudiant',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('short_name', models.CharField(max_length=10, verbose_name='Abbréviation')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('number', models.IntegerField(verbose_name='Numero de semestre')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('uid', models.UUIDField(blank=True, default=uuid.UUID('ad87375a-329b-4792-a6df-66f57a34b38a'))),
                ('first_name', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nom(s)')),
                ('serial_number', models.CharField(max_length=10, verbose_name='Matricule')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('region_of_origin', models.CharField(max_length=100, verbose_name="Region d'origine")),
                ('father_name', models.CharField(max_length=255, verbose_name='Nom(s) du père')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Nom(s) de la mère')),
                ('gender', models.CharField(choices=[('female', 'Feminin'), ('male', 'Masculin')], default='male', max_length=10, verbose_name='Sexe')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationnalité')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='VerbalProces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('academic_year', models.CharField(help_text='2015/2016', max_length=20, verbose_name='Année académique')),
                ('file', models.FileField(upload_to='proces/', verbose_name='Fichier procès verbal')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Procès verbal',
                'verbose_name_plural': 'Procès verbaux',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('course_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='app.CourseOfStudy')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/', verbose_name='fichier')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('ext', models.CharField(blank=True, max_length=10, verbose_name='extension')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.Document')),
            ],
            options={
                'verbose_name': 'Fichier du document',
                'verbose_name_plural': 'Fichiers du document',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Semester', verbose_name='Semestre concerné'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.Student', verbose_name='Etudiant'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.DocumentType'),
        ),
        migrations.AddField(
            model_name='courseofstudy',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_of_studies', to='app.Department'),
        ),
        migrations.AddField(
            model_name='courseofstudy',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='courses_of_studies', to='app.Student', verbose_name='Etudiants'),
        ),
        migrations.CreateModel(
            name='BachelorAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('academic_year', models.CharField(blank=True, max_length=10, verbose_name='Année académique')),
                ('father_occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation du père')),
                ('mother_occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation de la mère')),
                ('parents_address', models.CharField(blank=True, max_length=100, verbose_name='Adresse des parents')),
                ('bac_serial', models.CharField(blank=True, max_length=25, verbose_name='Série Bac')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Mention')),
                ('date_obtained', models.DateField(blank=True, verbose_name="Année d'obtention")),
                ('entry_qualification', models.CharField(blank=True, max_length=100, verbose_name="Diplôme d'entrée")),
                ('other_entry_qualification', models.CharField(blank=True, max_length=100, verbose_name="Autre diplôme d'entrée")),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Ville')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('course_of_study', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions_course', to='app.CourseOfStudy', verbose_name="Parcours de l'étudiant")),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bachelor_level', to='app.Level', verbose_name='Niveau')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Student', verbose_name='Etudiant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='admission/', verbose_name="Fiche d'inscription")),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('ext', models.CharField(max_length=10, verbose_name='Extension du fichier')),
                ('course_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CourseOfStudy', verbose_name='Parcours')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department', verbose_name='Departement')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level', verbose_name="Niveau d'étude")),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Speciality', verbose_name='Spécialité')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='app.Student', verbose_name='Etudiant')),
            ],
            options={
                'verbose_name': "Fiche d'admission",
                'verbose_name_plural': "Fiches d'admissions",
            },
        ),
    ]
