# Generated by Django 3.0.8 on 2020-09-16 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('8e343045-8a94-4e4f-9687-18edc2a582ca')),
        ),
    ]
