# Generated by Django 3.0.8 on 2020-08-09 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200806_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('798e687c-138c-4f1a-a587-46789c856244')),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'Feminin'), ('male', 'Masculin')], default='male', max_length=10, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='Nationnalité'),
        ),
    ]
