# Generated by Django 3.0.8 on 2020-09-16 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200916_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='region_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name="Region d'origine"),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('dd149708-242d-4187-bb4e-918dcda6447a')),
        ),
    ]
