# Generated by Django 3.0.8 on 2020-08-11 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200809_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('6ee5611d-d9c5-4e90-a7e4-b7690e083a1d')),
        ),
        migrations.CreateModel(
            name='AdmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='admission/', verbose_name="Fiche d'inscription")),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level', verbose_name="Niveau d'étude")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student', verbose_name='Etudiant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
