# Generated by Django 3.0.8 on 2020-09-16 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200916_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseofstudy',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('265e7318-273e-4326-b28e-b12ad87837c3')),
        ),
    ]
