# Generated by Django 3.0.8 on 2020-08-11 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200811_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.Student', verbose_name='Etudiant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionfile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='app.Student', verbose_name='Etudiant'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('887ab6aa-c9f6-4140-a4c7-f8273d25d363')),
        ),
    ]
