# Generated by Django 3.0.8 on 2020-08-12 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200811_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfile',
            name='ext',
            field=models.CharField(default='', max_length=10, verbose_name='Extension du fichier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionfile',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nom du fichier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('3dca3e37-99d9-4eef-9bdc-a4bb6cff882e')),
        ),
    ]
