# Generated by Django 3.0.8 on 2020-09-16 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200916_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionfile',
            name='speciality',
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('2b79ba34-de3f-4b2d-ab95-53d73e304fbc')),
        ),
    ]
