# Generated by Django 3.0.8 on 2020-08-12 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200812_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionfile',
            name='size',
            field=models.CharField(default=0, max_length=50, verbose_name='Taile du fichier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('8961a480-0ac2-42dd-a5eb-74eeae0d4b75')),
        ),
    ]
