# Generated by Django 3.0.8 on 2020-08-12 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200812_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionfile',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Taile du fichier'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('540982be-d351-48c1-9de6-c10c328211fc')),
        ),
    ]
