# Generated by Django 3.0.8 on 2020-09-16 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200916_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_of_study',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.CourseOfStudy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('3ca5e45f-6682-461d-83ab-5cdc74a5d302')),
        ),
    ]
