# Generated by Django 3.0.8 on 2020-08-12 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200812_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionfile',
            name='size',
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('dcef0bf3-94f0-4c3c-8a66-9aba491125d5')),
        ),
    ]
