# Generated by Django 3.0.8 on 2020-09-16 20:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200916_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.CourseOfStudy'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('7bab471c-f1a4-474b-bf1e-f6abdacac531')),
        ),
    ]
