# Generated by Django 3.0.8 on 2020-08-12 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200812_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='level',
        ),
        migrations.AddField(
            model_name='document',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Semester', verbose_name='Semestre concerné'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentfile',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nom du fichier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('a5e3d697-2c11-45c9-904f-8348bc51bc82')),
        ),
    ]
