# Generated by Django 3.0.8 on 2020-09-16 21:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200916_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verbal_proces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.VerbalProces', verbose_name='Procès verbal'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('070e0d23-c146-41a3-80fb-fe2f83bf1b38')),
        ),
    ]
