# Generated by Django 3.0.8 on 2020-08-12 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200812_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='a.png', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nom du fichier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('1e674797-8aa9-4771-a40b-1dbc7fd3d49b')),
        ),
    ]
