# Generated by Django 3.0.8 on 2020-09-08 12:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200812_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('07c36022-b564-4dcf-a577-68615cbf069e')),
        ),
        migrations.CreateModel(
            name='VerbalProces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('academic_year', models.CharField(help_text='2015/2016', max_length=20, verbose_name='Année académique')),
                ('file', models.FileField(upload_to='proces/', verbose_name='Fichier procès verbal')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level', verbose_name='Niveau')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
