# Generated by Django 3.0.8 on 2020-09-18 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200917_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(help_text='Format: jj/mm/annee', max_length=20, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.UUID('19ae062e-fd29-4542-b317-88dc921a0d61')),
        ),
    ]
